### Duplicates

In [20]:
import pandas as pd

data = {
    "name":["Yasir", "Yaseen", "Shahzain", "Amaar", "Yaseen"],
    "age" : [28, 34, 6, 3, 34],
    "city" : ["New York", "Larkana", "London", "Islamabad", "Larkana"]
}

df = pd.DataFrame(data)

#### 1. Duplicated
The `duplicated()` method returns a Boolean values for each row:

In [22]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

Filter the duplicated rows.

In [23]:
df[df.duplicated()]

     name  age     city
4  Yaseen   34  Larkana

To get the total number of duplicated rows.

In [24]:
df.duplicated().sum()

np.int64(1)

#### Drop Duplicate
The `drop_duplicate()` method in Pandas is design to remove duplicate rows from a DataFrame based on all columns or specific ones. By default, it scans the entire DataFrame and retains the first occurrence of each row and removes any duplicates that follow.

In [21]:
df_cleaned = df.drop_duplicates()
print(df_cleaned)

       name  age       city
0     Yasir   28   New York
1    Yaseen   34    Larkana
2  Shahzain    6     London
3     Amaar    3  Islamabad

#### 1. Drop Duplicates based on Specific Columns
We can remove duplicates in specific columns using the subset parameter.

In [13]:
data = {
    "name":["Yasir", "Yaseen", "Shahzain", "Amaar", "Yaseen"],
    "age" : [28, 34, 6, 3, 34],
    "city" : ["New York", "Larkana", "London", "Islamabad", "Larkana"]
}

df = pd.DataFrame(data)
df_cleaned = df.drop_duplicates(subset=["name"])
df_cleaned

       name  age       city
0     Yasir   28   New York
1    Yaseen   34    Larkana
2  Shahzain    6     London
3     Amaar    3  Islamabad

#### 2. Keeping the Last Occurrence of Duplicates
Be default `drop_duplicates` retains the first occurrence of duplicates. If we want to keep the last occurrence we can use `keep=last`.

In [14]:
df_cleaned = df.drop_duplicates(keep="last")

print("Original DataFrame")
print(df)

print("\nCleaned DataFrame (No Duplicate)")
print(df_cleaned)

Original DataFrame
       name  age       city
0     Yasir   28   New York
1    Yaseen   34    Larkana
2  Shahzain    6     London
3     Amaar    3  Islamabad
4    Yaseen   34    Larkana

Cleaned DataFrame (No Duplicate)
       name  age       city
0     Yasir   28   New York
2  Shahzain    6     London
3     Amaar    3  Islamabad
4    Yaseen   34    Larkana

#### 3. Dropping All Duplicates
If we want to remove all rows that are duplicates, we can `keep=False`.

With `keep=False` both occurrences of Alice are removed leaving only the rows with unique values across all columns.

In [15]:
df_cleaned = df.drop_duplicates(keep=False)

print("Original DataFrame")
print(df)

print("\nCleaned DataFrame (No Duplicate)")
print(df_cleaned)

Original DataFrame
       name  age       city
0     Yasir   28   New York
1    Yaseen   34    Larkana
2  Shahzain    6     London
3     Amaar    3  Islamabad
4    Yaseen   34    Larkana

Cleaned DataFrame (No Duplicate)
       name  age       city
0     Yasir   28   New York
2  Shahzain    6     London
3     Amaar    3  Islamabad

#### 4. Modifying the original DataFrame Directly
If we want to modify the DataFrame in place without creating a new DataFrame set `inplace=True`.

In [18]:
df.drop_duplicates(inplace=True)
print(df)

       name  age       city
0     Yasir   28   New York
1    Yaseen   34    Larkana
2  Shahzain    6     London
3     Amaar    3  Islamabad