### Sorting
Sorting data is an important step in data analysis as it helps to organize and structure the information for easier interpretation and decision-making. Whether we're working with small datasets or large ones, sorting allows us to arrange data in a meaningful way.

Pandas provides the `sort_values()` method which allows us to sort a DataFrame by one or more columns in either ascending or descending order.

#### 1. Sorting a DataFrame by a Single Column
The `sort_values()` method in Pandas makes it easy to sort our DataFrame by a single column. By default, it sorts in ascending order but we can customize this.

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 80]}
df = pd.DataFrame(data)

df.sort_values(by="Score")

      Name  Age  Score
3    David   40     80
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

In [5]:
df.sort_values(by="Score", ascending=False)

      Name  Age  Score
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85
3    David   40     80

Parameters of sort_values():
- `by`: Specifies the column to sort by.
- `ascending`: A boolean (True for ascending, False for descending).
- `inplace`: If True, the original DataFrame is modified otherwise a new sorted DataFrame is returned.
- `na_position`: Controls where NaN values are placed. Use 'first' to put NaNs at the top or 'last' (default) to place them at the end.
- `ignore_index`: If True, resets the index after sorting.

#### 2. Sorting a DataFrame by Multiple Columns
This is useful when we want to sort by one column like age and if there are ties, sort by another column like salary.

In [6]:
df.sort_values(by=["Age", "Score"])

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

#### 3. Sorting DataFrame with Missing Values
By default sort_values() places NaN values at the end. If we need them at the top, we can use the na_position parameter.

In [8]:
data_with_nan = {"Name": ["Alice", "Bob", "Charlie", "David"],"Age": [28, 22, None, 22]}
df_nan = pd.DataFrame(data_with_nan)
sorted_df = df_nan.sort_values(by="Age", na_position="first")
sorted_df

      Name   Age
2  Charlie   NaN
1      Bob  22.0
3    David  22.0
0    Alice  28.0

#### 4. Sorting by Index
By default, `sort_index()` sorts the DataFrame based on the index in ascending order.

In [9]:
df.sort_index()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [10]:
df.sort_index(ascending=False)

      Name  Age  Score
3    David   40     80
2  Charlie   35     95
1      Bob   30     90
0    Alice   25     85

#### 5. Choosing a Sorting Algorithm
Pandas provides different sorting algorithms that we can choose using the kind parameter.

In [14]:
# 1. QuickSort
print(df.sort_values(by="Age", kind="quicksort"))

# 2. MergeSort
print(df.sort_values(by="Score", kind="mergesort"))

# 3. HeapSort
print(df.sort_values(by=["Age", "Score"], kind="heapsort"))

Quick Sort:       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80
      Name  Age  Score
3    David   40     80
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80