## What is Pandas?
- Pandas is a Python library used for working with data sets.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

In [1]:
import pandas as pd

#### What is a Series?
- A Pandas Series is like a column in a table.

- It is a one-dimensional array holding data of any type.

In [3]:
nums = [1, 7, 8]

pd.Series(nums)

0    1
1    7
2    8
dtype: int64

#### Create Labels
With the `index` argument, you can name your own labels.

In [8]:
nums = [10, 20, 30]
s = pd.Series(nums, index=['a', 'b', 'c'])

In [9]:
s['b']

np.int64(20)

#### Key/Value Objects as Series
You can also use a key/value object, like a dictionary, when creating a Series.

`Note: The keys of the dictionary become the labels.`

In [10]:
days = {"Mon": 1, "Tue": 2, "Wed": 3, "Thur": 4, "Fri": 5, "Sat": 6, "Sun": 7}
pd.Series(days)

Mon     1
Tue     2
Wed     3
Thur    4
Fri     5
Sat     6
Sun     7
dtype: int64

#### DataFrames
- Data sets in Pandas are usually multi-dimensional tables, called DataFrame.
- Series is like a column, a DataFrame is the whole table.

In [14]:
data = [
    {"calories" : 420, "duration" : 50},
    {"calories" : 240, "duration" : 30},
    {"calories" : 500, "duration" : 60},
]
pd.DataFrame(data)

   calories  duration
0       420        50
1       240        30
2       500        60
   calories  duration
0       420        50
1       240        30
2       500        60

Preferred way to make dataframes

In [16]:
data = {
    "calories" : [420, 240, 500],
    "duration" : [50, 30, 60]
}
df = pd.DataFrame(data)

#### Locate Row
As you can see from the result above, the DataFrame is like a table with rows and columns.

Pandas use the `loc` attribute to return one or more specified row(s)

In [18]:
# Refer to the row index:
df.loc[0]

calories    420
duration     50
Name: 0, dtype: int64

Note: This example returns a Pandas Series.

In [19]:
type(df.loc[0])

pandas.Series

Return row 0 and 1:

In [20]:
# Use a list of indexes:
df.loc[[0, 1]]

   calories  duration
0       420        50
1       240        30

Note: When using `[ ]`, the result is a Pandas DataFrame.

In [21]:
type(df.loc[[0, 1]])

pandas.DataFrame

#### Named Indexes
With the `index` argument, you can name your own indexes.

In [25]:
inventory = {
    "name" : ["Laptop", "Mouse", "Keyboard"],
    "price": [540.12, 12.9, 29.5]
}

df = pd.DataFrame(inventory, index=["item1", "item2", "item3"])
print(df)

           name   price
item1    Laptop  540.12
item2     Mouse   12.90
item3  Keyboard   29.50

#### Locate Named Indexes
Use the named index in the `loc` attribute to return the specified row(s).

In [26]:
# Refer to the named index:
print(df.loc["item1"])

name     Laptop
price    540.12
Name: item1, dtype: object

#### Read CSV Files
- A simple way to store big data sets is to use CSV files (comma separated files).
- CSV files contains plain text and is well know format that can be read by everyone including Pandas.

In [31]:
df_csv = pd.read_csv("data.csv")
print(df_csv)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### Read JSON
- Big data sets are often stored, or extracted as JSON.
- JSON is plain text, but has format of an object, and is well known in the world of programming, including Pandas.

In [32]:
df_json = pd.read_json("data.json")
print(df_json)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#### Viewing the Data
- One of most used method for getting a quick overview of the DataFrame, is the `head()` method.
- The `head()` method returns the headers and a specified number or rows, starting from the top.

`Note: if the number of rows is not specified, the head() method will return the top 5 rows.`

In [35]:
df = pd.read_csv("data.csv")

df.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [37]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

- There is also `tail()` method for viewing the last rows of the DataFrame.
- The `tail()` method returns the headers and a specified number of rows, starting from the bottom.

In [39]:
print(df.tail())

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### Info About the Data
The DataFrames object has a method called `info()`, that gives you more information about the data set.

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB