### Selecting and Filtering Data
This operation retrieves specific columns, rows or records that match a condition. It allows precise extraction of required information.

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("data.csv")

In [10]:
df.head()

              name  age       city category  sales  a   b
0             John   25    Karachi        A    200  5  10
1              Ali   22    Larkana        B    120  2   3
2      Emmar Hyder   30  Islamabad        A    250  7   8
3        Ameer Ali   27     Lahore        C    300  4   6
4  Shahzain Yaseen   35  Hyderabad        B    200  1   9

In [15]:
df['age'] >= 30

0    False
1    False
2     True
3    False
4     True
Name: age, dtype: bool

Returns rows where `age` greater or equal to 30

In [16]:
df[ df['age'] >= 30 ]

              name  age       city category  sales  a  b
2      Emmar Hyder   30  Islamabad        A    250  7  8
4  Shahzain Yaseen   35  Hyderabad        B    200  1  9

In [23]:
df[ (df['age'] > 22) & (df['sales'] > 200) ]

          name  age       city category  sales  a  b
2  Emmar Hyder   30  Islamabad        A    250  7  8
3    Ameer Ali   27     Lahore        C    300  4  6

In [18]:
df[ df['name'].str.contains("Ali")]

        name  age     city category  sales  a  b
1        Ali   22  Larkana        B    120  2  3
3  Ameer Ali   27   Lahore        C    300  4  6

#### Adding and Removing Columns
You can create new columns based on existing ones or delete unwanted columns from the DataFrame

In [24]:
df['total'] = df['a'] + df['b']

print(df.head())

              name  age       city category  sales  a   b  total
0             John   25    Karachi        A    200  5  10     15
1              Ali   22    Larkana        B    120  2   3      5
2      Emmar Hyder   30  Islamabad        A    250  7   8     15
3        Ameer Ali   27     Lahore        C    300  4   6     10
4  Shahzain Yaseen   35  Hyderabad        B    200  1   9     10

In [25]:
df.drop(columns=['category'], inplace=True)

print(df.head())

              name  age       city  sales  a   b  total
0             John   25    Karachi    200  5  10     15
1              Ali   22    Larkana    120  2   3      5
2      Emmar Hyder   30  Islamabad    250  7   8     15
3        Ameer Ali   27     Lahore    300  4   6     10
4  Shahzain Yaseen   35  Hyderabad    200  1   9     10