### 1. Concatenation in Pandas

Concatenation means combining two or more DataFrames or Series together.

For example, a company stores January sales and February sales in separate DataFrames. You can combine them into one dataset.

In [1]:
import pandas as pd

jan_sales = pd.DataFrame({
    "product": ["Laptop", "Phone"],
    "sales": [50000, 30000]
})

feb_sales = pd.DataFrame({
    "product": ["Tablet", "Monitor"],
    "sales": [20000, 15000]
})

result = pd.concat([jan_sales, feb_sales], ignore_index=True)

print(result)

   product  sales
0   Laptop  50000
1    Phone  30000
2   Tablet  20000
3  Monitor  15000

Here, `pd.concat()` combines the rows, while `ignore_index=True` creates a fresh index from 0.

#### Row-wise concatenation - axis=0

Adds rows vertically. This is the default.

In [2]:
pd.concat([jan_sales, feb_sales], axis=0)

   product  sales
0   Laptop  50000
1    Phone  30000
0   Tablet  20000
1  Monitor  15000

#### Column-wise concatenation - axis=1

Adds columns horizontally, aligning rows by index.

In [3]:
pd.concat([jan_sales, feb_sales], axis=1)

  product  sales  product  sales
0  Laptop  50000   Tablet  20000
1   Phone  30000  Monitor  15000

#### 2. Apply and Map in Pandas
These methods help you transform data by applying a function or mapping values to new values.

#### A. `Series.map()`

In [16]:
employees = pd.DataFrame({
    "name": ["Ali", "Ahmed", "Zoya"],
    "department_id": [1, 2, 1]
})

departments = {
    1: "Engineering",
    2: "Marketing"
}

employees['department'] = employees['department_id'].map(departments)

employees

    name  department_id   department
0    Ali              1  Engineering
1  Ahmed              2    Marketing
2   Zoya              1  Engineering

`Notice that map() looks up each code in the dictionary and returns its corresponding name.`

#### B. `DataFrame.apply()`

Use apply() to apply a function to rows or columns of a DataFrame.

Example: Calculate the average marks of each student.

In [30]:
df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed"],
    "math": [80, 90, 70],
    "science": [85, 95, 75]
})

df["average"] = df[['math', 'science']].apply(
    lambda row: row.mean(),
    axis=1
)

df["total"] = df[['math', 'science']].apply(
    lambda row: row.sum(),
    axis=1
)

df["Result"] = df[['math', 'science']].apply(
    lambda row: row.mean(),
    axis=1
).apply(
    lambda row: "Pass" if row >= 80 else "Fail"
)

df

    name  math  science  average  total Result
0    Ali    80       85     82.5    165   Pass
1   Sara    90       95     92.5    185   Pass
2  Ahmed    70       75     72.5    145   Fail

The key part is `axis=1`, which means apply the function to each row.

`axis=0`: Apply the function to each column.

`axis=1`: Apply the function to each row.

#### C. `Series.apply()`

This applies a function to each value in a Series.

In [32]:
products = pd.DataFrame({
    "name": ["Laptop", "Mobile", "Keyboard"],
    "price": [5000, 1012, 540]
})

products["discounted_price"] = products['price'].apply(
    lambda price: price * 0.9
)

products

       name  price  discounted_price
0    Laptop   5000            4500.0
1    Mobile   1012             910.8
2  Keyboard    540             486.0

Each price is multiplied by 0.9, giving a 10% discount.

#### D. `DataFrame.map()`

In modern Pandas, DataFrame.map() applies a function element by element to an entire DataFrame.

In [34]:
df = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

df.map(lambda x: x * 10)

    A   B
0  10  30
1  20  40

### 3. Date and Time Data in Pandas
Date and time operations let you analyze information based on days, months, years, timestamps, and time differences.

For example, you might want to calculate monthly sales, find orders placed after a particular date, or determine delivery time.

#### A. Convert strings to datetime

Dates are sometimes stored as strings. Use pd.to_datetime() to convert them into proper datetime values.

In [40]:
df = pd.DataFrame({
    "order_date": ["2026-01-15", "2026-02-20", "2026-03-10"],
    "sales": [500, 700, 900]
})

df['order_date'] = pd.to_datetime(df["order_date"], )
print(df.dtypes)

order_date    datetime64[us]
sales                  int64
dtype: object

Now Pandas recognizes order_date as a datetime column rather than ordinary text.

#### B. Extract year, month, and day

Pandas provides the .dt accessor for datetime columns.

In [42]:
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["day"] = df["order_date"].dt.day
df

  order_date  sales  year  month  day
0 2026-01-15    500  2026      1   15
1 2026-02-20    700  2026      2   20
2 2026-03-10    900  2026      3   10

#### C. Filter by date

Suppose you want all orders placed after February 1, 2026.

In [44]:
df[df["order_date"] > "2026-02-01"]

  order_date  sales  year  month  day
1 2026-02-20    700  2026      2   20
2 2026-03-10    900  2026      3   10

#### D. Calculate time differences
Suppose you want to calculate how many days it took to deliver an order.

In [45]:
df = pd.DataFrame({
    "order_date": ["2026-01-01", "2026-01-10"],
    "delivery_date": ["2026-01-05", "2026-01-18"]
})

df["order_date"] = pd.to_datetime(df["order_date"])
df["delivery_date"] = pd.to_datetime(df["delivery_date"])

df["delivery_days"] = (
    df["delivery_date"] - df["order_date"]
).dt.days

In [46]:
df

  order_date delivery_date  delivery_days
0 2026-01-01    2026-01-05              4
1 2026-01-10    2026-01-18              8