### Grouping and Aggregating
Grouping and aggregation are used to summarize large datasets by dividing records into meaningful groups and calculating statistics for each group. Pandas provides `groupby()` and aggregation functions to perform these operations efficiently.

- It organizes records based on one or more columns.
- Calculates summaries such as total, average, minimum, maximum, and count.
- Grouped results can be further sorted, filtered, transformed, or reshaped.
- These operations are commonly used to analyze sales, customers, products, regions, and other categories.

In [3]:
import pandas as pd

data = {
    "Product": [
        "Laptop", "Phone", "Laptop", "Headphones",
        "Phone", "Keyboard", "Headphones", "Laptop"
    ],
    "Category": [
        "Electronics", "Electronics", "Electronics", "Accessories",
        "Electronics", "Accessories", "Accessories", "Electronics"
    ],
    "Region": [
        "North", "South", "North", "East",
        "South", "East", "North", "South"
    ],
    "Quantity": [2, 5, 3, 8, 4, 10, 6, 1],
    "Unit_Price": [60000, 25000, 60000, 3000, 25000, 2000, 3000, 60000],
    "Rating": [4.5, 4.2, 4.7, 4.0, 4.4, 4.1, 4.3, 4.8]
}

df = pd.DataFrame(data)

print(df)

      Product     Category Region  Quantity  Unit_Price  Rating
0      Laptop  Electronics  North         2       60000     4.5
1       Phone  Electronics  South         5       25000     4.2
2      Laptop  Electronics  North         3       60000     4.7
3  Headphones  Accessories   East         8        3000     4.0
4       Phone  Electronics  South         4       25000     4.4
5    Keyboard  Accessories   East        10        2000     4.1
6  Headphones  Accessories  North         6        3000     4.3
7      Laptop  Electronics  South         1       60000     4.8

#### Aggregating Data
Reduces a collection of values into a summary value. These methods can be applied directly to a Series or DataFrame when an overall summary is required.

- Use aggregation when individual records are not required in the result.
- Different functions answer different analytical questions.
- Aggregation can be performed before or after grouping data.

In [4]:
df['Quantity'].sum()

np.int64(39)

In [9]:
df['Rating'].mean()

np.float64(4.375)

In [11]:
df['Unit_Price'].median()

np.float64(25000.0)

In [12]:
df['Quantity'].min()

np.int64(1)

In [13]:
df['Quantity'].max()

np.int64(10)

In [14]:
df["Rating"].count()

np.int64(8)

In [15]:
df['Unit_Price'].std()

np.float64(26703.397322652196)

In [16]:
df['Unit_Price'].var()

np.float64(713071428.5714285)

In [17]:
df['Quantity'].agg(
    ['min', 'max', 'sum', 'mean']
)

min      1.000
max     10.000
sum     39.000
mean     4.875
Name: Quantity, dtype: float64

In [6]:
df['Quantity'].agg(
    minmum="min",
    maximum="max"
)

minmum      1
maximum    10
Name: Quantity, dtype: int64

In [11]:
df.agg(
    minimum_rating=("Rating", "min"),
    total_quantity = ("Quantity", "sum")
)

                Rating  Quantity
minimum_rating     4.0       NaN
total_quantity     NaN      39.0

### Grouping Data
Aggregation becomes more useful when calculations need to be performed separately for different categories. The groupby() method divides the DataFrame into groups based on one or more columns.

- `groupby()` defines how records should be divided.
- An aggregation function can then be applied to each group.
- Grouping does not change the original DataFrame unless the result is assigned back.

Single Column

In [34]:
df.groupby(['Product'])['Quantity'].sum()

Product
Headphones    14
Keyboard      10
Laptop         6
Phone          9
Name: Quantity, dtype: int64

Multiple Columns

In [35]:
df.groupby(["Category", "Product"])['Unit_Price'].sum()

Category     Product
Accessories  Headphones      6000
             Keyboard        2000
Electronics  Laptop        180000
             Phone          50000
Name: Unit_Price, dtype: int64

In [9]:
df.groupby(["Category", "Product"])['Unit_Price'].agg(
    Total = ("sum"),
    Maximum = ("max")
)

                         Total  Maximum
Category    Product
Accessories Headphones    6000     3000
            Keyboard      2000     2000
Electronics Laptop      180000    60000
            Phone        50000    25000

In [10]:
df.groupby(["Category", "Product"]).agg(
    Total = ('Unit_Price', "sum"),
    Maximum = ('Unit_Price', "max"),
    Average = ('Unit_Price', "mean")
)

                         Total  Maximum  Average
Category    Product
Accessories Headphones    6000     3000   3000.0
            Keyboard      2000     2000   2000.0
Electronics Laptop      180000    60000  60000.0
            Phone        50000    25000  25000.0