Pandas joins are used to combine data from two DataFrames using a common column or index.

Imagine you have two tables: one contains employee details, and another contains their salaries. You can join them to get all the information in one table.

In [24]:
import pandas as pd

employees = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "name": ["Ali", "Sara", "Ahmed"]
})

salaries = pd.DataFrame({
    "employee_id": [1, 2, 4],
    "salary": [50000, 60000, 70000]
})

### 2. The four main types of joins

Pandas supports four common join types through `pd.merge()`.

- inner = matching rows only.
- left = everything from the left table.
- right = everything from the right table.
- outer = everything from both tables.

#### 1. Inner join

Keeps only rows whose keys exist in both DataFrames.

In [25]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id  name  salary
0            1   Ali   50000
1            2  Sara   60000

#### 2. Left join

Keeps every row from the left DataFrame (employees) and matches salary data where available.

In [28]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name   salary
0            1    Ali  50000.0
1            2   Sara  60000.0
2            3  Ahmed      NaN

#### 3. Right join

Keeps every row from the right DataFrame (salaries) and matches employee data where available.

In [29]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id  name  salary
0            1   Ali   50000
1            2  Sara   60000
2            4   NaN   70000

#### 4. Outer (full) join

Keeps all rows from both DataFrames, matching IDs wherever possible.

In [30]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name   salary
0            1    Ali  50000.0
1            2   Sara  60000.0
2            3  Ahmed      NaN
3            4    NaN  70000.0

| Method | Main Purpose |
|---|---|
| `pd.merge()` | Combines DataFrames using common columns or indexes. |
| `df.join()` | Combines DataFrames primarily using indexes. |